export interface ObaLocationSeed {
  key: string
  label: string
  city: string
  state: string
  referenceCep: string
  enabledMarketIds?: string[]
}

export const OBA_LOCATION_SEEDS: ObaLocationSeed[] = [
  { key: "americana-centro-sp", label: "Americana - Centro, SP", city: "Americana", state: "SP", referenceCep: "13465520" },
  { key: "americana-jardim-sao-paulo-sp", label: "Americana - Jardim Sao Paulo, SP", city: "Americana", state: "SP", referenceCep: "13466550" },
  { key: "bauru-vila-aviacao-sp", label: "Bauru - Vila Aviacao, SP", city: "Bauru", state: "SP", referenceCep: "17018711", enabledMarketIds: ["barracao", "tenda", "samsclub", "tauste", "confianca", "atacadao", "oba"] },
  { key: "barueri-alphaville-farm-sp", label: "Barueri - Alphaville Farm, SP", city: "Barueri", state: "SP", referenceCep: "06455000" },
  { key: "barueri-alphaville-iguatemi-sp", label: "Barueri - Alphaville Iguatemi, SP", city: "Barueri", state: "SP", referenceCep: "06454905" },
  { key: "brasilia-105-sul-df", label: "Brasilia - 105 Sul, DF", city: "Brasilia", state: "DF", referenceCep: "70340000" },
  { key: "brasilia-209-norte-df", label: "Brasilia - 209 Norte, DF", city: "Brasilia", state: "DF", referenceCep: "70854500" },
  { key: "brasilia-212-sul-df", label: "Brasilia - 212 Sul, DF", city: "Brasilia", state: "DF", referenceCep: "70297700" },
  { key: "brasilia-302-sudoeste-df", label: "Brasilia - 302 Sudoeste, DF", city: "Brasilia", state: "DF", referenceCep: "70294000" },
  { key: "brasilia-306-norte-df", label: "Brasilia - 306 Norte, DF", city: "Brasilia", state: "DF", referenceCep: "70745000" },
  { key: "brasilia-araucarias-df", label: "Brasilia - Araucarias, DF", city: "Brasilia", state: "DF", referenceCep: "71910000" },
  { key: "brasilia-castanheiras-df", label: "Brasilia - Castanheiras, DF", city: "Brasilia", state: "DF", referenceCep: "71900100" },
  { key: "brasilia-colorado-taquari-df", label: "Brasilia - Colorado/Taquari, DF", city: "Brasilia", state: "DF", referenceCep: "70297400" },
  { key: "brasilia-iguatemi-df", label: "Brasilia - Shopping Iguatemi, DF", city: "Brasilia", state: "DF", referenceCep: "71503504" },
  { key: "brasilia-lago-sul-qi09-df", label: "Brasilia - Lago Sul QI 09, DF", city: "Brasilia", state: "DF", referenceCep: "70297700" },
  { key: "brasilia-lago-sul-smdb-df", label: "Brasilia - Lago Sul SMDB, DF", city: "Brasilia", state: "DF", referenceCep: "70297600" },
  { key: "brasilia-vicente-pires-df", label: "Brasilia - Vicente Pires, DF", city: "Brasilia", state: "DF", referenceCep: "72005710" },
  { key: "campinas-alphaville-sp", label: "Campinas - Alphaville/Arborais, SP", city: "Campinas", state: "SP", referenceCep: "13098035" },
  { key: "campinas-amoreiras-sp", label: "Campinas - Amoreiras, SP", city: "Campinas", state: "SP", referenceCep: "13036225" },
  { key: "campinas-bonfim-sp", label: "Campinas - Bonfim, SP", city: "Campinas", state: "SP", referenceCep: "13070000" },
  { key: "campinas-cambui-1-sp", label: "Campinas - Cambui I, SP", city: "Campinas", state: "SP", referenceCep: "13025152" },
  { key: "campinas-cambui-2-sp", label: "Campinas - Cambui II, SP", city: "Campinas", state: "SP", referenceCep: "13010000" },
  { key: "campinas-carolina-florence-sp", label: "Campinas - Carolina Florence, SP", city: "Campinas", state: "SP", referenceCep: "13073076" },
  { key: "campinas-centro-sp", label: "Campinas - Centro, SP", city: "Campinas", state: "SP", referenceCep: "13013050" },
  { key: "campinas-galleria-sp", label: "Campinas - Galleria, SP", city: "Campinas", state: "SP", referenceCep: "13091605" },
  { key: "campinas-nova-campinas-sp", label: "Campinas - Nova Campinas, SP", city: "Campinas", state: "SP", referenceCep: "13092133" },
  { key: "campinas-ponte-preta-sp", label: "Campinas - Ponte Preta, SP", city: "Campinas", state: "SP", referenceCep: "13041317" },
  { key: "campinas-sousas-sp", label: "Campinas - Sousas, SP", city: "Campinas", state: "SP", referenceCep: "13104000" },
  { key: "campinas-the-mall-sp", label: "Campinas - The Mall, SP", city: "Campinas", state: "SP", referenceCep: "13085000" },
  { key: "cotia-granja-viana-sp", label: "Cotia - Granja Viana, SP", city: "Cotia", state: "SP", referenceCep: "06709900" },
  { key: "franca-sp", label: "Franca, SP", city: "Franca", state: "SP", referenceCep: "14403000" },
  { key: "goiania-flamboyant-go", label: "Goiania - Flamboyant/Jardim Goias, GO", city: "Goiania", state: "GO", referenceCep: "74063340" },
  { key: "goiania-setor-bueno-go", label: "Goiania - Setor Bueno T-63, GO", city: "Goiania", state: "GO", referenceCep: "74230100" },
  { key: "indaiatuba-sp", label: "Indaiatuba, SP", city: "Indaiatuba", state: "SP", referenceCep: "13333055" },
  { key: "itatiba-sp", label: "Itatiba, SP", city: "Itatiba", state: "SP", referenceCep: "13255350" },
  { key: "itu-sp", label: "Itu, SP", city: "Itu", state: "SP", referenceCep: "13309050" },
  { key: "jundiai-sp", label: "Jundiai, SP", city: "Jundiai", state: "SP", referenceCep: "13240000" },
  { key: "limeira-sp", label: "Limeira, SP", city: "Limeira", state: "SP", referenceCep: "13480002" },
  { key: "piracicaba-sp", label: "Piracicaba, SP", city: "Piracicaba", state: "SP", referenceCep: "13414900" },
  { key: "ribeirao-preto-sp", label: "Ribeirao Preto, SP", city: "Ribeirao Preto", state: "SP", referenceCep: "14080140" },
  { key: "ribeirao-preto-farm-sp", label: "Ribeirao Preto - Farm, SP", city: "Ribeirao Preto", state: "SP", referenceCep: "14020260" },
  { key: "santos-sp", label: "Santos, SP", city: "Santos", state: "SP", referenceCep: "11065400" },
  { key: "sao-jose-dos-campos-sp", label: "Sao Jose dos Campos, SP", city: "Sao Jose dos Campos", state: "SP", referenceCep: "12243000" },
  { key: "sao-jose-do-rio-preto-sp", label: "Sao Jose do Rio Preto - Damha, SP", city: "Sao Jose do Rio Preto", state: "SP", referenceCep: "15061505" },
  { key: "sao-paulo-analia-franco-sp", label: "Sao Paulo - Analia Franco, SP", city: "Sao Paulo", state: "SP", referenceCep: "03338000" },
  { key: "sao-paulo-butanta-sp", label: "Sao Paulo - Butanta, SP", city: "Sao Paulo", state: "SP", referenceCep: "05339003" },
  { key: "sao-paulo-campo-belo-sp", label: "Sao Paulo - Campo Belo, SP", city: "Sao Paulo", state: "SP", referenceCep: "04615003" },
  { key: "sao-paulo-higienopolis-sp", label: "Sao Paulo - Higienopolis/Angelica, SP", city: "Sao Paulo", state: "SP", referenceCep: "01227000" },
  { key: "sao-paulo-interlagos-sp", label: "Sao Paulo - Interlagos, SP", city: "Sao Paulo", state: "SP", referenceCep: "04650000" },
  { key: "sao-paulo-itaim-bibi-sp", label: "Sao Paulo - Itaim Bibi, SP", city: "Sao Paulo", state: "SP", referenceCep: "04543000" },
  { key: "sao-paulo-market-place-sp", label: "Sao Paulo - Market Place, SP", city: "Sao Paulo", state: "SP", referenceCep: "04583903" },
  { key: "sao-paulo-moema-sp", label: "Sao Paulo - Moema, SP", city: "Sao Paulo", state: "SP", referenceCep: "04523001" },
  { key: "sao-paulo-mooca-sp", label: "Sao Paulo - Mooca, SP", city: "Sao Paulo", state: "SP", referenceCep: "03176000" },
  { key: "sao-paulo-morumbi-sp", label: "Sao Paulo - Morumbi, SP", city: "Sao Paulo", state: "SP", referenceCep: "05726130" },
  { key: "sao-paulo-pamplona-sp", label: "Sao Paulo - Pamplona, SP", city: "Sao Paulo", state: "SP", referenceCep: "01405000" },
  { key: "sao-paulo-penha-sp", label: "Sao Paulo - Penha, SP", city: "Sao Paulo", state: "SP", referenceCep: "03653000" },
  { key: "sao-paulo-perdizes-sp", label: "Sao Paulo - Perdizes, SP", city: "Sao Paulo", state: "SP", referenceCep: "05017000" },
  { key: "sao-paulo-pinheiros-sp", label: "Sao Paulo - Pinheiros/Teodoro Sampaio, SP", city: "Sao Paulo", state: "SP", referenceCep: "05406100" },
  { key: "sao-paulo-santana-ataliba-sp", label: "Sao Paulo - Santana Ataliba, SP", city: "Sao Paulo", state: "SP", referenceCep: "02033010" },
  { key: "sao-paulo-santana-pujol-sp", label: "Sao Paulo - Santana Pujol, SP", city: "Sao Paulo", state: "SP", referenceCep: "02016001" },
  { key: "sao-paulo-santana-tolle-sp", label: "Sao Paulo - Santana Tolle, SP", city: "Sao Paulo", state: "SP", referenceCep: "02404001" },
  { key: "sao-paulo-santo-andre-sp", label: "Santo Andre, SP", city: "Santo Andre", state: "SP", referenceCep: "09080110" },
  { key: "sao-paulo-sao-bernardo-do-campo-sp", label: "Sao Bernardo do Campo, SP", city: "Sao Bernardo do Campo", state: "SP", referenceCep: "09770000" },
  { key: "sao-paulo-tatuape-sp", label: "Sao Paulo - Tatuape, SP", city: "Sao Paulo", state: "SP", referenceCep: "03322002" },
  { key: "sao-paulo-tatuape-farm-sp", label: "Sao Paulo - Tatuape Farm, SP", city: "Sao Paulo", state: "SP", referenceCep: "03311002" },
  { key: "sao-paulo-vila-leopoldina-sp", label: "Sao Paulo - Vila Leopoldina, SP", city: "Sao Paulo", state: "SP", referenceCep: "05315010" },
  { key: "sao-paulo-vila-mariana-sp", label: "Sao Paulo - Vila Mariana, SP", city: "Sao Paulo", state: "SP", referenceCep: "04010903" },
  { key: "sao-paulo-vila-mascote-sp", label: "Sao Paulo - Vila Mascote, SP", city: "Sao Paulo", state: "SP", referenceCep: "04378300" },
  { key: "sao-paulo-vila-prudente-sp", label: "Sao Paulo - Vila Prudente/Ibitirama, SP", city: "Sao Paulo", state: "SP", referenceCep: "03133200" },
  { key: "sao-paulo-whitaker-sp", label: "Sao Paulo - Vila Mariana 2, SP", city: "Sao Paulo", state: "SP", referenceCep: "04014901" },
  { key: "sorocaba-alem-ponte-sp", label: "Sorocaba - Alem Ponte, SP", city: "Sorocaba", state: "SP", referenceCep: "18015000" },
  { key: "sorocaba-centro-sp", label: "Sorocaba - Centro, SP", city: "Sorocaba", state: "SP", referenceCep: "18046000" },
] as const
